@startuml

!pragma layout smetana
'skinparam groupInheritance 2
hide empty members


package product_definition_schema {
  class product_definition_relationship
  class product_definition
  }
product_definition_relationship -right-> product_definition : relating_product_definition
product_definition_relationship -right-> product_definition : related_product_definition

class product_definition_usage
product_definition_usage -up-|> product_definition_relationship

class assembly_component_usage {
  reference_designator : OPTIONAL identifier
} 
assembly_component_usage -up-|> product_definition_usage


class quantified_assembly_component_usage {
  quantity : measure_with_unit
} 
quantified_assembly_component_usage -up-|> assembly_component_usage

specified_higher_usage_occurrence -up-|> assembly_component_usage
specified_higher_usage_occurrence --> assembly_component_usage : upper_usage
specified_higher_usage_occurrence --> ext_assembly_usage_occurrence : next_usage

class next_assembly_usage_occurrence {
product_definition_occurence_id : identifier
}
next_assembly_usage_occurrence -up-|> assembly_component_usage


class multi_level_reference_designator 
multi_level_reference_designator -up-|> assembly_component_usage

class promissory_usage_occurrence
promissory_usage_occurrence-up-|> assembly_component_usage

product_definition_usage_relationship -right-> product_definition_usage : retating
product_definition_usage_relationship -right-> product_definition_usage : retated

@enduml