@startuml


class topological_representation_item {
  permanent_aggregate_id : identifier
  permanent_id : identifier
}



topological_representation_item <|-- vertex
topological_representation_item <|-- edge
'topological_representation_item <|-- face_bound
topological_representation_item <|-- face
'topological_representation_item <|-- vertex_shell
'topological_representation_item <|-- wire_shell
'topological_representation_item <|-- connected_edge_set
'topological_representation_item <|-- connected_face_set
topological_representation_item <|-- loop


representation_item <|-- topological_representation_item



@enduml