@startuml bounded_curve

'skinparam groupInheritance 2
'!pragma layout smetana
hide empty members
skinparam Linetype ortho

class curve #White {
}

class bounded_curve #White  {
}

class polyline #White {
}

class trimmed_curve #White {
  +basis_curve : curve
  +trim_1 : SET[1:2] OF trimming_select
  +trim_2 : SET[1:2] OF trimming_select
  +sense_agreement : BOOLEAN
  +master_representation : trimming_preference
}

class b_spline_curve #White {
  +degree : INTEGER
  +control_points_list : LIST[2:?] OF cartesian_point
  +curve_form : b_spline_curve_form
  +closed_curve : LOGICAL
  +self_intersect : LOGICAL
  +upper_index_on_control_points : INTEGER
  +control_points : ARRAY[0:upper_index_on_control_points] OF cartesian_point
}

class rational_b_spline_curve #White {
  +weights_data : LIST[2:?] OF REAL
  +weights : ARRAY[0:upper_index_on_control_points] OF REAL
}

class bounded_pcurve #White {
}

class bounded_surface_curve #White {
}

<> diamond
<> diamond2

' Наследование
curve <|-- bounded_curve

diamond -up-|> bounded_curve
diamond2 -up- diamond

diamond -left- polyline
diamond -right- trimmed_curve
diamond2 -left- b_spline_curve
diamond2 -right- bounded_pcurve
diamond2 -- bounded_surface_curve

b_spline_curve <|-- rational_b_spline_curve

@enduml