@startuml
skinparam groupInheritance 2
!pragma layout smetana
hide empty members

class geometric_representation_item {
}

class curve {
}

class line {
  +pnt : cartesian_point
  +dir : vector
}

class ellipse {
  +position : axis2_placement
  +major_radius : length_measure
  +minor_radius : length_measure
}

class polyline {
  + base_points : LIST[1:] OF cartesian_point
}

class rational_b_spline_curve {
  + base_points : LIST[1:] OF cartesian_point
  + order : count_measure
  + knots : LIST[1:] OF ratio_measure
  + weights : LIST[1:] OF ratio_measure
}

class direction_inverted_curve {
  + basis_curve : curve
}

class trimmed_curve {
  + basis_curve : curve
  + trim_1 : point
  + trim_2 : point
}

class pcurve {
  +basis_surface : surface
  +reference_to_curve : definitional_representation
}

class curve_replica {
  +parent_curve : curve
  +transformation : cartesian_transformation_operator
}


' Наследование
geometric_representation_item <|-- curve

curve <|-- line
curve <|-- ellipse
curve <|-- polyline
curve <|-- rational_b_spline_curve
curve <|-- direction_inverted_curve
curve <|-- trimmed_curve
curve <|-- pcurve
curve <|-- curve_replica

@enduml