@startuml placement

!pragma layout smetana
'skinparam groupInheritance 2
hide empty members

class geometric_representation_item #White {
  +dim
}

class placement #White {
  +location : cartesian_point
}

class axis1_placement #White {
  +axis : OPTIONAL direction
  +z : direction
}

class axis2_placement_2d #White {
  +ref_direction : OPTIONAL direction
  +p : LIST[2:2] OF direction
}

class axis2_placement_3d #White {
  +axis : OPTIONAL direction
  +ref_direction : OPTIONAL direction
  +p : LIST[3:3] OF direction
}

' Наследование
geometric_representation_item <|-- placement
placement <|-- axis1_placement
placement <|-- axis2_placement_2d
placement <|-- axis2_placement_3d

@enduml