@startuml point

!pragma layout smetana
'skinparam groupInheritance 2
hide empty members

class geometric_representation_item #White {
  +dim
}

class point #White {
  }

class cartesian_point #White {
  +coordinates : LIST[1:3] OF length_measure
}

class point_on_curve #White {
  +parameter : parameter_value
}

class curve #White {
}

class point_on_surface #White {
  +point_parameter_u : parameter_value
  +point_parameter_v : parameter_value
}
class surface #White {
}

' Наследование
geometric_representation_item <|-- point
point <|-- cartesian_point
point <|-- point_on_curve
point <|-- point_on_surface
' Связи
point_on_curve --> curve : basis_curve
point_on_surface --> surface : basis_surface
@enduml