@startuml surface

'!pragma layout smetana
'skinparam groupInheritance 2
hide empty members
'skinparam Linetype ortho
skinparam Nodesep 50

class surface #White {
}

class elementary_surface #White {
  +position : axis2_placement_3d
}

class plane #White {
}

class cylindrical_surface #White {
  +radius : positive_length_measure
}

class cylindrical_surface #White {
  +radius : length_measure
  +semi_angle : plane_angle_measure
WHERE
  WR1: radius > 0.0;
}


class conical_surface #White {
  +radius : length_measure
  +semi_angle : plane_angle_measure
WHERE
  WR1: radius >= 0.0;
  WR2: semi_angle > -PI*0.5;
  WR3: semi_angle < PI*0.5;
}

class spherical_surface #White {
  +radius : positive_length_measure
  WHERE
  WR1: radius > 0.0;
}

class toroidal_surface #White {
  +major_radius : positive_length_measure
  +minor_radius : positive_length_measure
  WHERE
  WR1: major_radius >= 0.0;
  WR1: minor_radius >= 0.0;
}

class degenerate_toroidal_surface #White {
  +select_outer : BOOLEAN
WHERE
  WR1: major_radius < minor_radius;
}

class ration_b_spline_surface #White {
  + degree_u : count_measure
  + degree_v : count_measure
  + closed_u : BOOLEAN
  + closed_v : BOOLEAN
  + base_points : LIST[1:LIST[1:]] of point
  + knots_u : LIST[1:] of ratio_measure
  + knots_v : LIST[1:] of ratio_measure
  + weights : LIST[1:LIST[1:]] of ratio_measure
  WHERE
  WR1: degree_u > 0;
  WR2: degree_v > 0;
}

class curve_bounded_surface #White {
  +basis_surface : surface
  +bounds : LIST[1:] of pcurve
}

class offset_surface #White {
  +basis_surface : surface
  +distance : length_measure
  +self_intersect : LOGICAL
}

class surface_replica #White {
  +basis_surface : surface
  +transformation : cartesian_transformation_operator
}

class bounded_surface #White {

}

<> diamond
<> diamond2
<> diamond3
<> diamond4
<> diamond5


' Наследование
diamond -up-|> surface
diamond2 -up- diamond
diamond3 -up- diamond2

diamond -left- elementary_surface
diamond -right- ration_b_spline_surface
diamond2 -right- bounded_surface
diamond2 -left- curve_bounded_surface
diamond3 -- offset_surface
diamond3 -- surface_replica

diamond4 -up-|> elementary_surface
diamond5 -up- diamond4

diamond5 -left- cylindrical_surface
diamond5 -right- conical_surface
diamond4 -right- plane
diamond4 -left- spherical_surface
diamond5 -- toroidal_surface

toroidal_surface <|-- degenerate_toroidal_surface

@enduml