@startuml
!pragma layout smetana
skinparam groupInheritance 2
hide empty members

class surface {
}

class elementary_surface {
  +position : axis2_placement_3d
}

class plane {
}

class cylindrical_surface {
  +radius : positive_length_measure
}

class cylindrical_surface {
  +radius : length_measure
  +semi_angle : plane_angle_measure
WHERE
  WR1: radius > 0.0;
}


class conical_surface {
  +radius : length_measure
  +semi_angle : plane_angle_measure
WHERE
  WR1: radius >= 0.0;
  WR2: semi_angle > -PI*0.5;
  WR3: semi_angle < PI*0.5;
}

class spherical_surface {
  +radius : positive_length_measure
  WHERE
  WR1: radius > 0.0;
}

class toroidal_surface {
  +major_radius : positive_length_measure
  +minor_radius : positive_length_measure
  WHERE
  WR1: major_radius >= 0.0;
  WR1: minor_radius >= 0.0;
}

class degenerate_toroidal_surface {
  +select_outer : BOOLEAN
WHERE
  WR1: major_radius < minor_radius;
}

class ration_b_spline_surface {
  + degree_u : count_measure
  + degree_v : count_measure
  + base_points : LIST[1:LIST[1:]] of point
  + knots_u : LIST[1:] of ratio_measure
  + knots_v : LIST[1:] of ratio_measure
  + weights : LIST[1:LIST[1:]] of ratio_measure
  WHERE
  WR1: degree_u > 0;
  WR2: degree_v > 0;
}

class curve_bounded_surface {
  +basis_surface : surface
  +bounds : LIST[1:] of pcurve
}

class offset_surface {
  +basis_surface : surface
  +distance : length_measure
  +self_intersect : LOGICAL
}

class surface_replica {
  +basis_surface : surface
}

' Наследование
surface <|-- bounded_surface
surface <|-- elementary_surface
surface <|-- ration_b_spline_surface
surface <|-- curve_bounded_surface
surface <|-- offset_surface
surface <|-- surface_replica

elementary_surface <|-- plane
elementary_surface <|-- cylindrical_surface
elementary_surface <|-- conical_surface
elementary_surface <|-- spherical_surface
elementary_surface <|-- toroidal_surface

toroidal_surface <|-- degenerate_toroidal_surface

@enduml