@startuml volume

'!pragma layout smetana
'skinparam groupInheritance 2
hide empty members


class geometric_representation_item #White {
}

class volume #White {
  +position : axis2_placement_3d
}

class block_volume #White {
  +x : positive_length_measure
  +y : positive_length_measure
  +z : positive_length_measure
}

class wedge_volume #White {
  +x : positive_length_measure
  +y : positive_length_measure
  +z : positive_length_measure
  +ltx : length_measure
}

class pyramid_volume #White {
  +xlength : positive_length_measure
  +ylength : positive_length_measure
  +height : positive_length_measure
}

class tetrahedron_volume #White {
  +point_1 : cartesian_point
  +point_2 : cartesian_point
  +point_3 : cartesian_point
  +point_4 : cartesian_point
}

class hexahedron_volume #White {
  +points : LIST[8:8] OF cartesian_point
}

class spherical_volume #White {
  +radius : positive_length_measure
}

class cylindrical_volume #White {
  +radius : positive_length_measure
  +height : positive_length_measure
}

class eccentric_conical_volume #White {
  +semi_axis_1 : positive_length_measure
  +semi_axis_2 : positive_length_measure
  +height : positive_length_measure
  +x_offset : length_measure
  +y_offset : length_measure
  +ratio : REAL
}

class toroidal_volume #White {
  +major_radius : positive_length_measure
  +minor_radius : positive_length_measure
}

class ellipsoid_volume #White {
  +semi_axis_1 : positive_length_measure
  +semi_axis_2 : positive_length_measure
  +semi_axis_3 : positive_length_measure
}

<> diamond
<> diamond2
<> diamond3
<> diamond4
<> diamond5

' Наследование
geometric_representation_item <|-- volume

diamond -up-|> volume
diamond2 -up- diamond
diamond3 -up- diamond2
diamond4 -up- diamond3
diamond5 -up- diamond4

diamond -left- block_volume
diamond -right- wedge_volume
diamond2 -left- pyramid_volume
diamond2 -right- tetrahedron_volume
diamond3 -left- hexahedron_volume
diamond3 -right- spherical_volume
diamond4 -left- cylindrical_volume
diamond4 -right- eccentric_conical_volume
diamond5 -- toroidal_volume
diamond5 -- ellipsoid_volume

@enduml