@startuml
skinparam groupInheritance 2

class условие {
  +наименование
  }

class "условная применяемость" {
  +наименование
  +описание
}

class "условная конфигурация" {
  +тип конфигурации
  +тип наследования
}

class "применяемость по датам" {
  +идентификатор
  +дата окончания
  +дата начала
}

class применяемость {
  +идентификатор
  +название
  +описание
}

class "связь применяемостей" {
  +название
  +описание
}

class "применяемость по партии" {
  +идентификатор
  +номер партии
  +размер партии
}

class "применяемость по серийным номерам" {
  +идентификатор
  +идентификатор_начала
  +идентификатор_окончания
}

class "применяемость по времени" {
  +идентификатор
  +период_применяемости
}

' Наследование
применяемость <|-- "применяемость по датам"
применяемость <|-- "применяемость по партии"
применяемость <|-- "применяемость по серийным номерам"
применяемость <|-- "применяемость по времени"

' Ассоциации для множественного наследования
условие <|-- "условная применяемость"
применяемость <|-- "условная применяемость"
"условная применяемость" <|-- "условная конфигурация"

' Связи
"связь применяемостей" --> применяемость : связанная_применяемость
"связь применяемостей" --> применяемость : связывающая_применяемость

@enduml