@startuml qualified_measure

'!pragma layout smetana
hide empty methods
'skinparam Nodesep 150
skinparam Linetype polyline


class representation_item #White {
  
}

class descriptive_representation_item #White {
  + description : text
}

class expanded_uncertainty #White {
  + coverage_factor : REAL
}

class maths_value_qualification #White {
  + name : label
  + description : text
}
'переменные следущего класса не приведены в схеме express
class maths_value_representation_item #White {
  value_component : maths_value
  unit_component : unit
}

class measure_qualification #White {
  + name : label
  + description : text
}

class measure_representation_item #White {

}

class maths_value_precision_qualifier #White {

}

class precision_qualifier #White {
  + precision_value : INTEGER
}

class qualified_representation_item #White {

}

class qualitative_uncertainty #White {
  + uncertainty_value : text
}

class standard_uncertainty #White {
  + uncertainty_value : REAL
}

class type_qualifier #White {
  + name : label
}

class uncertainty_qualifier #White {
  + measure_name : label
  + description : text
}

class value_format_type_qualifier #White {
 
}

class value_format_type #White {
    + id : identifier
}

class maths_value_with_unit #White {

}

class measure_with_unit #White {

}

class maths_value #White {

}

enum value_qualifier #White {
    precision_qualifier
    value_format_type_qualifier
    type_qualifier
    uncertainty_qualifier
    maths_value_precision_qualifier
}

<> diamond

' Связи между классами

diamond -up-|> representation_item

descriptive_representation_item -up- diamond

expanded_uncertainty -up-|> standard_uncertainty

maths_value_qualification -down-> maths_value_with_unit : qualified_maths_value
maths_value_qualification --> value_qualifier : qualifiers SET [1:?]

maths_value_representation_item -up- diamond
maths_value_representation_item --> maths_value_with_unit

measure_qualification --> measure_with_unit : qualified_measure
measure_qualification --> value_qualifier : qualifiers SET [1:?]

measure_representation_item -up- diamond
measure_representation_item --> measure_with_unit : value_component 

qualified_representation_item -up- diamond
qualified_representation_item --> value_qualifier : qualifiers SET [1:?]

qualitative_uncertainty -up-|> uncertainty_qualifier


standard_uncertainty -up-|> uncertainty_qualifier


value_format_type_qualifier --> value_format_type : format_type

maths_value_precision_qualifier  -right-> maths_value : precision_value

maths_value_with_unit --> maths_value : value_component
maths_value_with_unit -right-> unit : unit_component

@enduml