@startuml

class product {
  +id : identifier
  +name : label
  +description : OPTIONAL text
  +frame_of_reference : SET [1:?] OF product_context
}

class product_definition_formation {
  +id : identifier
  +description : OPTIONAL text
}

class product_definition_formation_with_specified_source {
  +make_or_buy : source
}
class product_definition_formation_relationship {
  +id : identifier
  +name : label
  +description : OPTIONAL text
}
class alternative_solution_relationship {
  +relation_type : STRING
}


' Наследование
product_definition_formation <|-- product_definition_formation_with_specified_source
alternative_solution_relationship --|> product_definition_formation_relationship
' Связи между классами
product <-- product_definition_formation : of_product


product_definition_formation_relationship --> product_definition_formation : relating_product_definition_formation
product_definition_formation_relationship --> product_definition_formation : related_product_definition_formation

@enduml