@startuml configuration_management

hide empty members

class configuration_design_item #White {
}

class configurable_item #White {
  + id : identifier
  + name : label
  - description : text?
  +item_concept : product_concept
  - purpose : label?
}

class configuration_design #White {
  + name : label
  + description : text?
}

class configuration_effectivity #White {
}

class configuration_item #White {
  + id : identifier
  + name : label
  - description : text?
  - purpose : label?
  + item_concept : product_concept
}

class configuration_item_relationship #White {
  +name : label
  -description : text?

}

enum configuration_design_item #White {
   product_definition
   product_definition_formation
   product_definition_occurrence
}

configuration_item <|-- configurable_item
configuration_effectivity  <|-- product_definition_effectivity


configuration_item  --> product_concept : item_concept 

configurable_item "1" -- "1..*" product_concept_feature_association : item_concept_feature

configuration_design --> configuration_item : configuration
configuration_design --> configuration_design_item : design

configuration_effectivity --> configuration_design : configuration

configuration_item_relationship -left-> configuration_item : relating_configuration_item
configuration_item_relationship -left-> configuration_item : related_configuration_item

@enduml