@startuml

hide empty methods

class calendar_date #White {
  + day_component : day_in_month_number
  + month_component : month_in_year_number
}

class coordinated_universal_time_offset #White {
  +hour_offset : INTEGER
  - minute_offset : INTEGER?
  +sense : ahead_or_behind
  +actual_minute_offset : INTEGER
}

class date #White {
  year_component : year_number
}

class date_and_time #White {

}

class local_time #White {
  +hour_component : hour_in_day
  -minute_component : minute_in_hour?
  -second_component : second_in_minute?

}

class week_of_year_and_day_date #White {
  +week_component : week_in_year_number
  -day_component : day_in_week_number?
}

class year_month #White {
  month_component : month_in_year_number
}

' Связи между сущностями

calendar_date -up-|> date
week_of_year_and_day_date -up-|> date
year_month -up-|> date


date_and_time --> date : date_component
date_and_time --> local_time : time_component
local_time --> coordinated_universal_time_offset : zone



@enduml