@startuml
'skinparam groupInheritance 2
hide empty methods
'skinparam linetype ortho
'skinparam nodesep 150

class условие #White {
  +наименование
  }

class "условная применяемость" #White {
  +наименование
  +описание
}

class "условная конфигурация" #White {
  +тип конфигурации
  +тип наследования
}

class "применяемость по датам" #White {
  +идентификатор
  +дата окончания
  +дата начала
}

class применяемость #White {
  +идентификатор
  +название
  +описание
}

class "связь применяемостей" #White {
  +название
  +описание
}

class "применяемость по партии" #White {
  +идентификатор
  +номер партии
  +размер партии
}

class "применяемость по серийным номерам" #White {
  +идентификатор
  +идентификатор_начала
  +идентификатор_окончания
}

class "применяемость по времени" #White {
  + идентификатор
  + период_применяемости
}

<> diamond 

' Наследование
применяемость <|-down- diamond
diamond <|-- "применяемость по датам"
diamond <|-- "применяемость по партии"
diamond <|-- "применяемость по серийным номерам"
diamond <|-- "применяемость по времени"

' Ассоциации для множественного наследования
условие <|-- "условная применяемость"
применяемость <|-- "условная применяемость"
"условная применяемость" <|-- "условная конфигурация"

' Связи
"связь применяемостей" -right-> применяемость : связанная_применяемость
"связь применяемостей" --> применяемость : связывающая_применяемость

@enduml