@startuml representation

hide empty members

class representation #White {
  + id : identifier
  + name : label
  + description : text
}

abstract class representation_context #White {
  + context_identifier : identifier
  + context_type : text
}

class representation_item #White {

}

class definitional_representation #White {
}

class global_uncertainty_assigned_context #White {
  + uncertainty : SET [1:?] OF uncertainty_measure_with_unit
}


class parametric_representation_context #White {
}


class uncertainty_assigned_representation #White {
  + uncertainty : SET [1:?] OF uncertainty_measure_with_unit
}

abstract class uncertainty_measure_with_unit #White {
  + name : label
  - description : OPTIONAL text
}

' Связи между классами

definitional_representation -up-|> representation
global_uncertainty_assigned_context -up-|> representation_context
parametric_representation_context -up-|> representation_context
uncertainty_assigned_representation -up-|> representation



representation --> representation_item : items
representation --> representation_context : context_of_items

global_uncertainty_assigned_context -right-> uncertainty_measure_with_unit : uncertainty
uncertainty_assigned_representation --> uncertainty_measure_with_unit : uncertainty

@enduml