@startuml

hide empty members

class measure_value #White {
}

class unit #White {
}

class named_unit #White {
}

class representation_context #White {   
}

class dimensional_exponents #White {
    + length_exponent : REAL
    + mass_exponent : REAL
    + time_exponent : REAL
    + electric_current_exponent : REAL
    + thermodynamic_temperature_exponent : REAL
    + amount_of_substance_exponent : REAL
    + luminous_intensity_exponent : REAL
  }


' Сущности
class global_unit_assigned_context #White {
}

class measure_with_unit #White {
}

class plane_angle_unit #White {
}

' Наследование
global_unit_assigned_context -up-|> representation_context

plane_angle_unit -up-|> named_unit

named_unit -up-|> unit

' Ассоциации
global_unit_assigned_context --> unit : units
measure_with_unit -right-> unit : unit_component
measure_with_unit --> measure_value : value_component
named_unit -right-> dimensional_exponents : dimentions



@enduml